apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aurora
resources:
- namespace.yaml
- aurora-deployment.yaml
commonLabels:
  app.kubernetes.io/name: aurora
  app.kubernetes.io/component: core
